version: '3.7'

services:
  zerotier:
    image: letfn/zerotier
    env_file: .env
    network_mode: host
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    devices:
    - /dev/net/tun
    volumes:
    - ./etc/zerotier:/var/lib/zerotier-one
    restart: always
