version: '3.4'
services:
  zerotier:
    image: letfn/zerotier
    restart: always
    network_mode: host
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    devices:
    - /dev/net/tun
    volumes:
    - /data/zerotier:/var/lib/zerotier-one
