version: '3.7'

services:
  zerotier:
    image: defn/zerotier
    env_file: .env
    network_mode: host
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - CAP_SYS_RAWIO
    devices:
    - /dev/net/tun
    volumes:
    - ${ZT_MOUNT}/zerotier:/var/lib/zerotier-one
    - env_zerotier:/secrets
    restart: always

volumes:
  env_zerotier:
    external: true
