#!/usr/bin/env sh

function ztjoin {
  while ! zerotier-cli info | grep ONLINE; do
    echo "waiting for ONLINE $(date)"
    sleep 1;
  done

  zerotier-cli join "$(cat /data/config/ZT_NETWORK)"

  while true; do
    ZT_IP="$(ifconfig "$(zerotier-cli listnetworks | grep OK | awk '{print $8}')" | grep 'inet addr' | awk '{print $2}' | cut -d: -f2-)"
    if [[ -n "${ZT_IP}" ]]; then
      break
    fi
    echo "waiting for JOIN $(date)"
    sleep 1;
  done
}

function main {
  set -exfu
  
  if [[ -f /data/config/ZT_NETWORK ]]; then
    ztjoin &
  fi

  exec /main.sh zerotier-one
}

main "$@"
