#!/usr/bin/env sh

function ztjoin {
  while ! zerotier-cli info | grep ONLINE; do
    echo "waiting for ONLINE $(date)"
    sleep 1;
  done

  zerotier-cli join "$(cat /data/config/ZT_NETWORK)"

  while true; do
    ZT_IP="$(ifconfig "$(zerotier-cli listnetworks | grep OK | awk '{print $8}')" | grep 'inet addr' | awk '{print $2}' | cut -d: -f2-)"
    if [[ -n "${ZT_IP}" ]]; then
      break
    fi
    echo "waiting for JOIN $(date)"
    sleep 1;
  done

  local zt_vip="$(cat /data/config/ZT_VIP 2>/dev/null || true)"
  if [[ -n "${zt_vip}" ]]; then
    local ip_eth0="$(ifconfig eth0 | grep 'inet addr:' | awk '{print $2}' | cut -d: -f2)"
    iptables -t nat -A PREROUTING --dst "${zt_vip}" -p tcp --dport 80 -j DNAT --to-destination "${ip_eth0}"
    iptables -t nat -A PREROUTING --dst "${zt_vip}" -p tcp --dport 443 -j DNAT --to-destination "${ip_eth0}"
  fi

  local zt_dest="$(cat /data/config/ZT_DEST 2>/dev/null || true)"
  if [[ -n "${zt_dest}" ]]; then
    socat tcp4-listen:22,reuseaddr,fork "TCP:${zt_dest}:22" &
    socat tcp4-listen:80,reuseaddr,fork "TCP:${zt_dest}:80" &
    socat tcp4-listen:443,reuseaddr,fork "TCP:${zt_dest}:443" &
    socat tcp4-listen:1194,reuseaddr,fork "TCP:${zt_dest}:1194" &
  fi
}

function main {
  set -exfu
  
  if [[ -f /data/config/ZT_NETWORK ]]; then
    ztjoin &
  fi

  exec /main.sh zerotier-one
}

main "$@"
