#!/usr/bin/env bash

function ztjoin {
  while ! zerotier-cli info | grep ONLINE; do
    echo "waiting for ONLINE $(date)"
    sleep 1;
  done

  if [[ -n "${ZT_NETWORK:-}" ]]; then
    zerotier-cli join "${ZT_NETWORK}"
  fi

  while true; do
    ZT_IP="$(ifconfig "$(zerotier-cli listnetworks | grep OK | awk '{print $8}')" | grep 'inet ' | awk '{print $2}' | cut -d: -f2-)"
    if [[ -n "${ZT_IP}" ]]; then
      export ZT_IP
      break
    fi
    echo "waiting for JOIN $(date)"
    sleep 1;
  done

  if [[ -n "${ZT_VIP:-}" ]]; then
    local zt="$(zerotier-cli listnetworks | grep "${ZT_NETWORK}" | awk '{print $8}')"
    ip addr add "${ZT_VIP:-}/32" dev "${zt}" || true
    ifconfig -a "${zt}"
  fi

  echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
  sysctl -p
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

  if [[ -x /service.d/hook-customize ]]; then
    /service.d/hook-customize
  fi
}

function main {
  set -a
  source /secrets/.env
  set +a

  set -exfu
  
  if [[ -x /service.d/hook-start ]]; then
    /service.d/hook-start
  fi

  if [[ -n "${ZT_IDENTITY_SECRET:-}" ]]; then
    echo -n "${ZT_IDENTITY_PUBLIC}" > /var/lib/zerotier-one/identity.public
    echo -n "${ZT_IDENTITY_SECRET}" > /var/lib/zerotier-one/identity.secret
    echo -n "${ZT_AUTHTOKEN_SECRET}" > /var/lib/zerotier-one/authtoken.secret
  fi

  if [[ -n "${ZT_NETWORK:-}" ]]; then
    ztjoin &
  fi

  chown zerotier-one:zerotier-one /dev/net/tun
  exec /main.sh zerotier-one 2>/tmp/stderr.log 1>/tmp/stdout.log
}

main "$@"
